### ISSUE TITLE
Disabled Button Style

### ISSUE THREAD

**Issue by edodso2** [sdodson99/show-n-tell#11]
When using the app I clicked the outline button multiple times not knowing it was a disabled button. Commonly disabled buttons just have a lower opacity then the default primary button. For example bootstrap:

<img width="917" alt="image" src="https://user-images.githubusercontent.com/12009947/79931581-50086e00-8419-11ea-9c40-f286dbebf22f.png">

**Comment by sdodson99** [comment]
That's a good point. Do you think removing the border would fix this issue?

**Comment by edodso2** [comment]
Honestly border is part of it but I think its mainly how the text of the button is so solid. Since that is where the user is most focused. If you lighten up the text/increase opacity it will go a long way.

Or you can follow bootstrap style above and just drop the opacity to .5 and remove hover effect when disabled. Bootstrap style philosophy is that even when the button is disabled you can still tell it is a primary button and not a secondary style button.

**Comment by sdodson99** [comment]
Reduced opacity looks great!
